Added Scheduler.py
DipanshKhandelwal/PythonScripts pull request #103
Opened 2018-10-04 12:05 UTC by matosBrent

### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).

#### Type of Change

- [ ] Bug fix
- [x] New implementation

### PR Description

Fixes #[Add issue number here.]

2018-10-04 13:28 UTC, DipanshKhandelwal requested changes

2018-10-04 13:28 UTC, DipanshKhandelwal commented on scripts/python/scheduler.py
> +                    with open('C:\Users\harvey\Desktop\Prod.txt','r+') as f:
It has local links. Please update the code

2018-10-04 13:28 UTC, DipanshKhandelwal commented on scripts/python/scheduler.py
> +                    with open('C:\Users\harvey\Desktop\Prod.txt','r+') as f:
here

2018-10-04 13:28 UTC, DipanshKhandelwal commented on scripts/python/scheduler.py
> +                    with open('C:\Users\harvey\Desktop\Prod.txt','r+') as f:
here

2018-10-04 13:28 UTC, DipanshKhandelwal commented on scripts/python/scheduler.py
> +                    webbrowser.open_new_tab('C:\Users\harvey\Desktop\Prod.txt')
and many places like this. Please update it.

2018-10-06 20:14 UTC, matosBrent commented
Changes done @DipanshKhandelwal

2018-10-23 17:58 UTC, DipanshKhandelwal approved these changes
Thanks

2018-10-23 17:58 UTC, merged